### ISSUE TITLE
Syntax sugar for some often cases

### ISSUE THREAD

**Issue by Strate** [schmittjoh/php-option#24]
While php's closure syntax is very explicit, it is very boring to write code like this:
```php
$repo->find(1)
  ->flatMap(function($object) { return $object->getNested(); })
  ->flatMap(function($nested) { return (string) $nested; })
  ->getOrElse('Not found!')
```

I suggest to add helper functions: `call` for this case:

```php
$repo->find(1)
  ->call('getNested')
  ->call('__toString')
  ->getOrElse('Not found')
```

Also I suggest to add `get` function, which can helps to get object's properties and array values:
```php
Some::create($object)
  ->get('property') // performs property_exists check and returns None if not found

Some::create($array)
  ->get($index) // performs array_key_exists check and returns None if not found
```

**Comment by Strate** [comment]
Oh, it already proposed in #16 , but this tells us, that feature requested.

**Comment by schmittjoh** [comment]
Yeah like I said there, I think the best way is to create some reusable functions that in turn create the closures you need.

There is probably already a library out there which does exactly that.

**Comment by Strate** [comment]
Or use your own fork ;-)

**Comment by schmittjoh** [comment]
Yep, that works, too :)

I'll close this here.
