### ISSUE TITLE
Build targets: 5.3 fails (remove); nothing for 7.0+

### ISSUE THREAD

**Issue by junglebarry** [schmittjoh/php-option#34]
Hi,

I notice that the master branch fails on PHP 5.3, which is old enough that I suspect it could safely be dropped from the Travis plan.

Would it be worth adding a 7.0+ build target to the Travis plan, for more recent releases?

Cheers!

**Comment by markcarver** [comment]
This repo seems to have stagnated, I've gone ahead and forked this project which currently supports PHP 5.3-7.3  and includes extensive testing for all versions:

https://github.com/unicorn-fail/php-option

**Comment by GrahamCampbell** [comment]
This will be fixed in the coming days, if not tonight. :)
