### ISSUE TITLE
composer install or composer require fail to download

### ISSUE THREAD

**Issue by setlec** [schmittjoh/php-option#53]
hello i'm using an laravel app where is package is required but when doing a composer install or composer require command it fails to download the package. Any idea on how to fix this issue. ;)

cordially and thanks in advance

![image](https://user-images.githubusercontent.com/1214602/74046977-dcd18d00-49cf-11ea-886b-79e616eebfe3.png)

**Comment by GrahamCampbell** [comment]
Doesn't look like an issue with this package?
