### ISSUE TITLE
Allow `getOrCall` to accept arguments for the callable 

### ISSUE THREAD

**Issue by mohamednagy** [schmittjoh/php-option#56]
The following is a suggestion for `getOrCall`
```
Option::fromValue('some-value')->getOrCall('abort', [404]);
```
the first parameter will be the callable and the second will be the arguments passed to the callble.

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion. This is already possible via:

```php
Option::fromValue('some-value')->getOrCall(function () { return abort(404); });
```

or in PHP 7.4+:

```php
Option::fromValue('some-value')->getOrCall(fn() => abort(404));
```

I'd need a little more convincing that we need more syntax over the native offerings for "thunking".
