### ISSUE TITLE
Laravel upgrade to 5.8 version

### ISSUE THREAD

**Issue by God9ps** [schmittjoh/php-option#57]
Hi, when I try to upgrade laravel from 5.7 version to 5.8 I get `Failed to download phpoption/phpoption from dist: The "https://api.github.com/repos/schmittjoh/php-option/zipball/994ecccd8f3283ecf5ac33254543eb0ac946d525" file could not be downloaded: failed to open stream`. 

I'm using the following core:

`"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "jenssegers/mongodb": "^3.4",
        "laravel/framework": "^5.7.0",
        "laravel/tinker": "^1.0",
        "lorisleiva/laravel-deployer": "^0.2.5",
        "maddhatter/laravel-fullcalendar": "^1.3",
        "pusher/pusher-php-server": "^3.2",
        "spatie/laravel-permission": "^2.16",
        "yajra/laravel-datatables": "^1.1",
        "yajra/laravel-datatables-oracle": "~8.0"
    },
    "require-dev": {
        "composer/composer": "^1.9",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0",
        "squizlabs/php_codesniffer": "3.*"
    },`
    
If I use 5.7 laravel version everything works fine.

    How can I solve this?

**Comment by GrahamCampbell** [comment]
This looks like an issue with your network or GitHub. Please contact GitHub support if this error persists.

**Comment by God9ps** [comment]
> This looks like an issue with your network or GitHub. Please contact GitHub support if this error persists.

When I run composer update it return an error and provides me a link to reset my GitHub token.
In my network I think isn't because I can run it in laravel 5.7 version.

**Comment by GrahamCampbell** [comment]
I don't understand why you're posting here? You can buy my consulting services if you'd like. I don't see what else I can offer?

**Comment by God9ps** [comment]
> I don't understand why you're posting here? You can buy my consulting services if you'd like. I don't see what else I can offer?

My intention is only to report a possible issue in this package and give my little contribute to improve. This issues section exists for that. But, thanks anyway.
