### ISSUE TITLE
Additional methods to isDefined and isEmpty

### ISSUE THREAD

**Issue by Wulfheart** [schmittjoh/php-option#70]
I think the methods for `isSome()` and `isNone()` would be a great addition as the classes are actually called like that. Would you be willing to merge this? Note: This would be a non-breaking change as they would also use `isDefined()` and `isEmpty()` under the hood.

**Comment by GrahamCampbell** [comment]
Thanks, but I'm not a fan of providing aliases unless we'd want to deprecate the originals. I prefer the original names.
